# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Get Last Lotto Number

on:
  schedule:
    - cron: '40 20 * * 6'
    - cron: '50 20 * * 6'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f lotto/requirements.txt ]; then pip install -r lotto/requirements.txt; fi
    - name: Run get_last_lotto.py
      run: |
        python lotto/get_last_lotto.py
    - name: Push file
      run: |
        git config --global user.name '이화영'
        git config --global user.email 'lightjade@gmail.com'
        git add -A
        git commit -am "add lotto result file"
        git push
